// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0dB8oeJ4ak1IqT-8wOlnojNnS9Kc3bJ0',
    appId: '1:147889231888:android:9ebc4ad2ab29880efbd295',
    messagingSenderId: '147889231888',
    projectId: 'ai-buddy-f8e69',
    storageBucket: 'ai-buddy-f8e69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyPHpe5jeVuTUqWedWnhgZUMYXpiyq6mk',
    appId: '1:147889231888:ios:75d1cf62963c8dc8fbd295',
    messagingSenderId: '147889231888',
    projectId: 'ai-buddy-f8e69',
    storageBucket: 'ai-buddy-f8e69.appspot.com',
    iosClientId: '147889231888-92r51q5l8gt627i7fpkdi6r8lilj6g8c.apps.googleusercontent.com',
    iosBundleId: 'com.ai.aiChatboat',
  );
}
